<a href="https://colab.research.google.com/github/YASHYOGESHAHIRE/02-value-investment-finance/blob/main/value_investment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
 import pandas as pd
 import numpy as np
 import yfinance as yf
 import math

In [4]:
tickers = pd.read_csv('/content/top_50_indian_stocks.csv')
tickers.head()

         Ticker               Company Name
0   RELIANCE.NS        Reliance Industries
1        TCS.NS  Tata Consultancy Services
2   HDFCBANK.NS                  HDFC Bank
3       INFY.NS                    Infosys
4  ICICIBANK.NS                 ICICI Bank

In [5]:
def fetch_values_of_stocks(tickers):
  value_cols=[
      "Ticker",
      "Price",
      "PE-ratio",
      "PB-ratio",
      "PS-ratio",
      "EV/EBITDA",
      "EV/GP"
  ]
  value_df=pd.DataFrame(columns=value_cols)
  for ticker in tickers:
    stock= yf.Ticker(ticker)

    price = np.nan # Default price to NaN
    hist_data = stock.history(period="1d")
    if not hist_data.empty and 'Close' in hist_data.columns and not hist_data['Close'].empty:
        price = hist_data['Close'].iloc[-1]
    else:
        print(f"Warning: No valid price data found for {ticker}. Assigning NaN.")

    # Initialize ratios to NaN
    pe_ratio, pb_ratio, ps_ratio, evEbitda, evGrossProfit = np.nan, np.nan, np.nan, np.nan, np.nan

    try:
        info = stock.info
        if info: # Ensure info dictionary is not empty
            pe_ratio = info.get("forwardPE", np.nan)
            pb_ratio = info.get("priceToBook", np.nan)
            ps_ratio = info.get("priceToSalesTrailing12months", np.nan)
            ev = info.get("enterpriseValue", np.nan)
            ebitda = info.get("ebitda", np.nan)

            if pd.notna(ev) and pd.notna(ebitda) and ebitda != 0:
                evEbitda = ev / ebitda

            grossMargins = info.get("grossMargins", np.nan)
            totalRevenue = info.get("totalRevenue", np.nan)

            grossProfit = np.nan
            if pd.notna(grossMargins) and pd.notna(totalRevenue):
                grossProfit = grossMargins * totalRevenue

            if pd.notna(ev) and pd.notna(grossProfit) and grossProfit != 0:
                evGrossProfit = ev / grossProfit
        else:
            print(f"Warning: No info data found for {ticker}. Assigning NaN to ratios.")

    except Exception as e:
        print(f"Error fetching info for {ticker}: {e}")

    value_df.loc[len(value_df)] = [ticker, price, pe_ratio, pb_ratio, ps_ratio, evEbitda, evGrossProfit]
  return value_df

In [6]:
ril=yf.Ticker("RELIANCE.NS")
ril.info

{'address1': 'Maker Chambers IV',
 'address2': '3rd Floor 222 Nariman Point',
 'city': 'Mumbai',
 'zip': '400021',
 'country': 'India',
 'phone': '91 22 3555 5000',
 'fax': '91 22 2204 2268',
 'website': 'https://www.ril.com',
 'industry': 'Oil & Gas Refining & Marketing',
 'industryKey': 'oil-gas-refining-marketing',
 'industryDisp': 'Oil & Gas Refining & Marketing',
 'sector': 'Energy',
 'sectorKey': 'energy',
 'sectorDisp': 'Energy',
 'longBusinessSummary': 'Reliance Industries Limited engages in hydrocarbon exploration and production, petroleum refining and marketing, petrochemicals, advanced materials and composites, renewable, financial services, retail, and digital services worldwide. It operates through the Oil to Chemicals, Oil and Gas, Retail, Digital Services, and Others segments. The company is involved in refining and marketing products, including liquefied petroleum gas, propylene, naphtha, gasoline, jet/aviation turbine fuel, kerosine oil, diesel, sulfur, and petroleum coke. It also provides polymers comprising high-density and low-density polyethylene (PE), linear low-density PE, homopolymer, random and impact copolymer, and polyvinyl chloride; fiber intermediates that include purified terephthalic acid, and ethylene glycols and oxide; aromatics, such as paraxylene, ortho xylene, benzene, and linear alkyl benzene and paraffin; and textiles that consist of fabrics, apparel, and auto furnishings. In addition, the company offers elastomers, such as polybutadiene rubber, styrene butadiene rubber, and butyl rubber; fiber and yarn polyesters; and bioenergy solutions, including compressed biogas, and pellets and briquettes. Further, it engages in oil and gas exploration and production activities; operation of various stores comprising supermarkets, hypermarket, wholesale cash and carry, specialty, and online stores; operation of media and entertainment platforms, and Network18 and television channels; and publishing of magazines. Additionally, the company provides highway hospitality and fleet management services, as well as digital services, such as connectivity, fiber, mobile devices, apps, business, and other digital solutions. Reliance Industries Limited was founded in 1957 and is based in Mumbai, India.',
 'fullTimeEmployees': 404501,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Mukesh Dhirubhai Ambani',
   'age': 68,
   'title': 'Chairman & MD',
   'yearBorn': 1957,
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Nikhil Rasiklal Meswani',
   'age': 59,
   'title': 'Executive Director',
   'yearBorn': 1966,
   'fiscalYear': 2026,
   'totalPay': 250000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hital Rasiklal Meswani',
   'age': 57,
   'title': 'Executive Director',
   'yearBorn': 1968,
   'fiscalYear': 2026,
   'totalPay': 250000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Panda Madhusudana Siva Prasad',
   'age': 73,
   'title': 'Executive Director',
   'yearBorn': 1952,
   'fiscalYear': 2026,
   'totalPay': 205800000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Anant Mukesh Ambani',
   'age': 30,
   'title': 'Whole-Time Director',
   'yearBorn': 1995,
   'fiscalYear': 2026,
   'totalPay': 123900000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Parul  Sharma',
   'title': 'Group President',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Srikanth  Venkatachari',
   'age': 59,
   'title': 'Chief Financial Officer',
   'yearBorn': 1966,
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Mahesh  Marve',
   'title': 'Head of Research & Technology',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hemen Kanu Modi',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Savithri  Parekh',
   'title': 'Company Secretary & Compliance Officer',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 9,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 9,
 'governanceEpochDate': 1780531200,
 'compensationAsOfEpochDate': 1798675200,
 'irWebsite': 'http://ril.com/html/investor/investor.html',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 1303.7,
 'open': 1304.5,
 'dayLow': 1288.0,
 'dayHigh': 1306.0,
 'regularMarketPreviousClose': 1303.7,
 'regularMarketOpen': 1304.5,
 'regularMarketDayLow': 1288.0,
 'regularMarketDayHigh': 1306.0,
 'dividendRate': 6.0,
 'dividendYield': 0.46,
 'exDividendDate': 1780617600,
 'payoutRatio': 0.0921,
 'fiveYearAvgDividendYield': 0.44,
 'beta': 0.182,
 'trailingPE': 21.646545,
 'forwardPE': 17.954712,
 'volume': 17783058,
 'regularMarketVolume': 17783058,
 'averageVolume': 19935394,
 'averageVolume10days': 17182369,
 'averageDailyVolume10Day': 17182369,
 'bid': 0.0,
 'ask': 0.0,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 17470422253568,
 'nonDilutedMarketCap': 18275604292217,
 'fiftyTwoWeekLow': 1288.0,
 'fiftyTwoWeekHigh': 1611.8,
 'allTimeHigh': 1611.8,
 'allTimeLow': 5.428648,
 'priceToSalesTrailing12Months': 1.6524885,
 'fiftyDayAverage': 1361.832,
 'twoHundredDayAverage': 1427.983,
 'trailingAnnualDividendRate': 6.0,
 'trailingAnnualDividendYield': 0.004602286,
 'currency': 'INR',
 'tradeable': False,
 'enterpriseValue': 20687311863808,
 'profitMargins': 0.0764,
 'floatShares': 6607365088,
 'sharesOutstanding': 13532472634,
 'heldPercentInsiders': 0.51181,
 'heldPercentInstitutions': 0.28788,
 'impliedSharesOutstanding': 13532472635,
 'bookValue': 668.045,
 'priceToBook': 1.9325047,
 'lastFiscalYearEnd': 1774915200,
 'nextFiscalYearEnd': 1806451200,
 'mostRecentQuarter': 1774915200,
 'earningsQuarterlyGrowth': -0.126,
 'netIncomeToCommon': 807750008832,
 'trailingEps': 59.64,
 'forwardEps': 71.90313,
 'pegRatio': 0.82,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1730073600,
 'enterpriseToRevenue': 1.957,
 'enterpriseToEbitda': 12.065,
 '52WeekChange': -0.08957291,
 'SandP52WeekChange': 0.27181315,
 'lastDividendValue': 6.0,
 'lastDividendDate': 1780617600,
 'quoteType': 'EQUITY',
 'currentPrice': 1291.0,
 'targetHighPrice': 1910.0,
 'targetLowPrice': 1510.0,
 'targetMeanPrice': 1696.1562,
 'targetMedianPrice': 1695.0,
 'recommendationMean': 1.3125,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 32,
 'totalCash': 2581470117888,
 'totalCashPerShare': 190.761,
 'ebitda': 1714649956352,
 'totalDebt': 3979999969280,
 'quickRatio': 0.585,
 'currentRatio': 1.098,
 'totalRevenue': 10572189925376,
 'debtToEquity': 36.653,
 'revenuePerShare': 781.246,
 'returnOnAssets': 0.03672,
 'returnOnEquity': 0.09139,
 'grossProfits': 3685560090624,
 'freeCashflow': 218291257344,
 'operatingCashflow': 1921130037248,
 'earningsGrowth': -0.126,
 'revenueGrowth': 0.125,
 'grossMargins': 0.34861,
 'ebitdaMargins': 0.16218,
 'operatingMargins': 0.099750005,
 'financialCurrency': 'INR',
 'symbol': 'RELIANCE.NS',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'CLOSED',
 'exchange': 'NSI',
 'messageBoardId': 'finmb_878373',
 'exchangeTimezoneName': 'Asia/Kolkata',
 'exchangeTimezoneShortName': 'IST',
 'gmtOffSetMilliseconds': 19800000,
 'market': 'in_market',
 'esgPopulated': False,
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 820467900000,
 'regularMarketChange': -12.699951,
 'regularMarketDayRange': '1288.0 - 1306.0',
 'fullExchangeName': 'NSE',
 'averageDailyVolume3Month': 19935394,
 'fiftyTwoWeekLowChange': 3.0,
 'fiftyTwoWeekLowChangePercent': 0.0023291926,
 'fiftyTwoWeekRange': '1288.0 - 1611.8',
 'fiftyTwoWeekHighChange': -320.80005,
 'fiftyTwoWeekHighChangePercent': -0.19903216,
 'fiftyTwoWeekChangePercent': -8.957291,
 'earningsTimestamp': 1777024800,
 'earningsTimestampStart': 1784282400,
 'earningsTimestampEnd': 1784282400,
 'earningsCallTimestampStart': 1745592300,
 'earningsCallTimestampEnd': 1745592300,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 59.64,
 'epsForward': 71.90313,
 'epsCurrentYear': 63.52712,
 'priceEpsCurrentYear': 20.32203,
 'fiftyDayAverageChange': -70.83203,
 'fiftyDayAverageChangePercent': -0.05201231,
 'twoHundredDayAverageChange': -136.98303,
 'twoHundredDayAverageChangePercent': -0.09592763,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 15,
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'regularMarketChangePercent': -0.9741467,
 'regularMarketPrice': 1291.0,
 'shortName': 'RELIANCE INDUSTRIES LTD',
 'longName': 'Reliance Industries Limited',
 'corporateActions': [],
 'regularMarketTime': 1780653600,
 'trailingPegRatio': None}

In [13]:
tickers_list=tickers['Ticker']
df=fetch_values_of_stocks(tickers_list)
df

ERROR:yfinance:$TATAMOTORS.NS: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Warning: No valid price data found for TATAMOTORS.NS. Assigning NaN.

ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}

,Ticker,Price,PE-ratio,PB-ratio,PS-ratio,EV/EBITDA,EV/GP
0,RELIANCE.NS,1291.000000,17.954712,1.932505,NaN,12.065035,5.613055
1,TCS.NS,2198.899902,13.291954,7.008960,NaN,10.856281,7.127766
2,HDFCBANK.NS,747.049988,11.888652,1.962265,NaN,NaN,NaN
3,INFY.NS,1197.500000,14.609312,5.198081,NaN,1093.840651,814.033092
4,ICICIBANK.NS,1262.099976,13.876246,2.489418,NaN,NaN,NaN
5,HINDUNILVR.NS,2121.500000,39.595154,10.227251,NaN,33.888950,15.124873
6,SBIN.NS,977.700012,9.529786,1.524414,NaN,NaN,NaN
7,BAJFINANCE.NS,889.400024,17.976105,4.850250,NaN,NaN,22.510702
8,BHARTIARTL.NS,1798.199951,21.551907,7.052594,NaN,10.440634,8.754300
9,ITC.NS,280.700012,15.856420,4.850862,NaN,12.106601,7.140017
10,KOTAKBANK.NS,377.450012,13.480357,2.072500,NaN,NaN,NaN
11,ADANIENT.NS,3048.199951,53.869400,4.869088,NaN,37.223687,10.765717
12,LT.NS,3953.199951,21.551163,4.975896,NaN,18.042499,5.685855
13,HCLTECH.NS,1154.699951,14.415482,4.098199,NaN,1077.190087,624.707787
14,ASIANPAINT.NS,2686.699951,45.893230,12.048360,NaN,38.038899,16.346470
15,AXISBANK.NS,1272.300049,10.097619,1.838270,NaN,NaN,NaN
16,SUNPHARMA.NS,1782.199951,27.516460,5.122030,NaN,24.282533,8.535052
17,WIPRO.NS,198.369995,13.785324,2.362926,NaN,10.168374,6.444878
18,ULTRACEMCO.NS,10912.000000,24.926277,4.455898,NaN,NaN,NaN
19,HDFCLIFE.NS,575.299988,46.924957,6.980356,NaN,58.832859,12.025826
20,ONGC.NS,264.750000,6.086708,0.895939,NaN,4.563303,1.962346
21,NTPC.NS,361.649994,12.782738,1.726714,NaN,8.364155,5.187402
22,POWERGRID.NS,285.649994,14.340636,2.642681,NaN,10.746495,8.733512
23,TATAMOTORS.NS,NaN,NaN,NaN,NaN,NaN,NaN
24,INDUSINDBK.NS,904.799988,12.481459,1.071794,NaN,NaN,NaN
25,ADANIGREEN.NS,1525.699951,49.477158,13.027922,NaN,33.400840,30.351249
26,TITAN.NS,4260.200195,49.756813,24.085938,NaN,48.435195,23.423066
27,DIVISLAB.NS,6623.000000,46.954030,10.482266,NaN,50.068627,26.640610
28,TECHM.NS,1483.500000,17.383010,4.441045,NaN,13.917303,6.212869
29,MARUTI.NS,13050.000000,21.038420,3.828925,NaN,18.318721,7.702384
30,COALINDIA.NS,472.299988,8.263483,2.443605,NaN,6.067859,1.957229
31,BPCL.NS,295.000000,7.436877,1.258677,NaN,3.741977,2.108563
32,JSWSTEEL.NS,1284.000000,17.656523,3.132242,NaN,12.629194,5.725965
33,DRREDDY.NS,1278.199951,19.814133,2.822730,NaN,15.514052,5.964326
34,BAJAJFINSV.NS,1703.199951,18.506260,3.490250,NaN,11.956322,8.789035
35,ADANIPORTS.NS,1824.199951,23.531855,4.379884,NaN,21.361324,19.217751
36,CIPLA.NS,1401.300049,22.177076,3.438512,NaN,17.899754,5.764807
37,BRITANNIA.NS,5120.500000,39.398956,24.154556,NaN,34.636099,15.309733
38,HAVELLS.NS,1150.500000,33.823135,7.632195,NaN,33.076413,9.550749
39,SHREECEM.NS,24085.000000,33.988667,9.431100,NaN,30.394816,12.989450
40,GRASIM.NS,3087.699951,21.028017,2.102374,NaN,13.216398,4.900219
41,TATASTEEL.NS,206.770004,10.998404,2.712769,NaN,10.450971,2.634354
42,HEROMOTOCO.NS,4835.000000,15.164440,4.475762,NaN,12.027232,5.386056
43,M&M.NS,3040.500000,18.991392,3.649543,NaN,10.737296,5.562058
44,EICHERMOT.NS,7070.000000,26.664543,7.726522,NaN,32.555689,18.214718
45,IOC.NS,138.259995,7.853276,0.867258,NaN,4.109124,2.093191
46,SBICARD.NS,589.599976,16.267838,3.569483,NaN,NaN,33.721651
47,PIDILITIND.NS,1476.599976,48.695374,13.877688,NaN,41.699376,18.089749
48,DMART.NS,4144.200195,58.444714,11.023334,NaN,52.403024,26.232405
49,HDFCAMC.NS,2495.899902,28.424921,11.586041,NaN,26.187872,23.755835

In [14]:

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Ticker     50 non-null     object
 1   Price      49 non-null     float64
 2   PE-ratio   49 non-null     float64
 3   PB-ratio   49 non-null     float64
 4   PS-ratio   0 non-null      float64
 5   EV/EBITDA  40 non-null     float64
 6   EV/GP      42 non-null     float64
dtypes: float64(6), object(1)
memory usage: 3.1+ KB

In [15]:
numeric_cols = [
    "Price",
    "PE-ratio",
    "PB-ratio",
    "PS-ratio",
    "EV/EBITDA",
    "EV/GP"
]
for col in numeric_cols:
  df[col]=df[col].fillna(df[col].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Ticker     50 non-null     object
 1   Price      50 non-null     float64
 2   PE-ratio   50 non-null     float64
 3   PB-ratio   50 non-null     float64
 4   PS-ratio   0 non-null      float64
 5   EV/EBITDA  50 non-null     float64
 6   EV/GP      50 non-null     float64
dtypes: float64(6), object(1)
memory usage: 3.1+ KB

In [10]:
from scipy import stats

In [16]:
percentile_metrics ={
    "PE-ratio" : "PE-Ratio_Percentile",
    "PB-ratio" : "PB-Ratio_Percentile",
    "PS-ratio" : "PS-Ratio_Percentile",
    "EV/EBITDA" : "EV/EBITDA_Percentile",
    "EV/GP" : "EV/GP_Percentile"
}
for metric,percentile in percentile_metrics.items():
  df[percentile]=df[metric].apply(lambda x: stats.percentileofscore(df[metric],x)/100)
df.head()

,Ticker,Price,PE-ratio,PB-ratio,PS-ratio,EV/EBITDA,EV/GP,PE-Ratio_Percentile,PB-Ratio_Percentile,PS-Ratio_Percentile,EV/EBITDA_Percentile,EV/GP_Percentile
0,RELIANCE.NS,1291.000000,17.954712,1.932505,NaN,12.065035,5.613055,0.46,0.16,NaN,0.28,0.20
1,TCS.NS,2198.899902,13.291954,7.008960,NaN,10.856281,7.127766,0.22,0.74,NaN,0.22,0.34
2,HDFCBANK.NS,747.049988,11.888652,1.962265,NaN,75.386413,45.309444,0.16,0.18,NaN,0.87,0.89
3,INFY.NS,1197.500000,14.609312,5.198081,NaN,1093.840651,814.033092,0.34,0.68,NaN,1.00,1.00
4,ICICIBANK.NS,1262.099976,13.876246,2.489418,NaN,75.386413,45.309444,0.28,0.28,NaN,0.87,0.89

In [18]:
from statistics import mean
df['Value Score'] = df[[value for value in percentile_metrics.values()]].mean(axis=1)
df

,Ticker,Price,PE-ratio,PB-ratio,PS-ratio,EV/EBITDA,EV/GP,PE-Ratio_Percentile,PB-Ratio_Percentile,PS-Ratio_Percentile,EV/EBITDA_Percentile,EV/GP_Percentile,Value Score
0,RELIANCE.NS,1291.000000,17.954712,1.932505,NaN,12.065035,5.613055,0.46,0.16,NaN,0.28,0.20,0.2750
1,TCS.NS,2198.899902,13.291954,7.008960,NaN,10.856281,7.127766,0.22,0.74,NaN,0.22,0.34,0.3800
2,HDFCBANK.NS,747.049988,11.888652,1.962265,NaN,75.386413,45.309444,0.16,0.18,NaN,0.87,0.89,0.5250
3,INFY.NS,1197.500000,14.609312,5.198081,NaN,1093.840651,814.033092,0.34,0.68,NaN,1.00,1.00,0.7550
4,ICICIBANK.NS,1262.099976,13.876246,2.489418,NaN,75.386413,45.309444,0.28,0.28,NaN,0.87,0.89,0.5800
5,HINDUNILVR.NS,2121.500000,39.595154,10.227251,NaN,33.888950,15.124873,0.84,0.84,NaN,0.60,0.56,0.7100
6,SBIN.NS,977.700012,9.529786,1.524414,NaN,75.386413,45.309444,0.10,0.10,NaN,0.87,0.89,0.4900
7,BAJFINANCE.NS,889.400024,17.976105,4.850250,NaN,75.386413,22.510702,0.48,0.58,NaN,0.87,0.68,0.6525
8,BHARTIARTL.NS,1798.199951,21.551907,7.052594,NaN,10.440634,8.754300,0.62,0.76,NaN,0.14,0.44,0.4900
9,ITC.NS,280.700012,15.856420,4.850862,NaN,12.106601,7.140017,0.38,0.60,NaN,0.30,0.36,0.4100
10,KOTAKBANK.NS,377.450012,13.480357,2.072500,NaN,75.386413,45.309444,0.24,0.20,NaN,0.87,0.89,0.5500
11,ADANIENT.NS,3048.199951,53.869400,4.869088,NaN,37.223687,10.765717,0.98,0.62,NaN,0.64,0.50,0.6850
12,LT.NS,3953.199951,21.551163,4.975896,NaN,18.042499,5.685855,0.60,0.64,NaN,0.42,0.22,0.4700
13,HCLTECH.NS,1154.699951,14.415482,4.098199,NaN,1077.190087,624.707787,0.32,0.48,NaN,0.98,0.98,0.6900
14,ASIANPAINT.NS,2686.699951,45.893230,12.048360,NaN,38.038899,16.346470,0.86,0.92,NaN,0.66,0.60,0.7600
15,AXISBANK.NS,1272.300049,10.097619,1.838270,NaN,75.386413,45.309444,0.12,0.14,NaN,0.87,0.89,0.5050
16,SUNPHARMA.NS,1782.199951,27.516460,5.122030,NaN,24.282533,8.535052,0.74,0.66,NaN,0.48,0.40,0.5700
17,WIPRO.NS,198.369995,13.785324,2.362926,NaN,10.168374,6.444878,0.26,0.24,NaN,0.12,0.32,0.2350
18,ULTRACEMCO.NS,10912.000000,24.926277,4.455898,NaN,75.386413,45.309444,0.70,0.54,NaN,0.87,0.89,0.7500
19,HDFCLIFE.NS,575.299988,46.924957,6.980356,NaN,58.832859,12.025826,0.88,0.72,NaN,0.76,0.52,0.7200
20,ONGC.NS,264.750000,6.086708,0.895939,NaN,4.563303,1.962346,0.02,0.04,NaN,0.06,0.04,0.0400
21,NTPC.NS,361.649994,12.782738,1.726714,NaN,8.364155,5.187402,0.20,0.12,NaN,0.10,0.14,0.1400
22,POWERGRID.NS,285.649994,14.340636,2.642681,NaN,10.746495,8.733512,0.30,0.30,NaN,0.20,0.42,0.3050
23,TATAMOTORS.NS,2718.009177,23.592273,5.753018,NaN,75.386413,45.309444,0.68,0.70,NaN,0.87,0.89,0.7850
24,INDUSINDBK.NS,904.799988,12.481459,1.071794,NaN,75.386413,45.309444,0.18,0.06,NaN,0.87,0.89,0.5000
25,ADANIGREEN.NS,1525.699951,49.477158,13.027922,NaN,33.400840,30.351249,0.94,0.94,NaN,0.58,0.78,0.8100
26,TITAN.NS,4260.200195,49.756813,24.085938,NaN,48.435195,23.423066,0.96,0.98,NaN,0.70,0.70,0.8350
27,DIVISLAB.NS,6623.000000,46.954030,10.482266,NaN,50.068627,26.640610,0.90,0.86,NaN,0.72,0.76,0.8100
28,TECHM.NS,1483.500000,17.383010,4.441045,NaN,13.917303,6.212869,0.42,0.52,NaN,0.36,0.30,0.4000
29,MARUTI.NS,13050.000000,21.038420,3.828925,NaN,18.318721,7.702384,0.58,0.46,NaN,0.44,0.38,0.4650
30,COALINDIA.NS,472.299988,8.263483,2.443605,NaN,6.067859,1.957229,0.08,0.26,NaN,0.08,0.02,0.1100
31,BPCL.NS,295.000000,7.436877,1.258677,NaN,3.741977,2.108563,0.04,0.08,NaN,0.02,0.08,0.0550
32,JSWSTEEL.NS,1284.000000,17.656523,3.132242,NaN,12.629194,5.725965,0.44,0.36,NaN,0.32,0.24,0.3400
33,DRREDDY.NS,1278.199951,19.814133,2.822730,NaN,15.514052,5.964326,0.54,0.34,NaN,0.38,0.28,0.3850
34,BAJAJFINSV.NS,1703.199951,18.506260,3.490250,NaN,11.956322,8.789035,0.50,0.40,NaN,0.24,0.46,0.4000
35,ADANIPORTS.NS,1824.199951,23.531855,4.379884,NaN,21.361324,19.217751,0.66,0.50,NaN,0.46,0.66,0.5700
36,CIPLA.NS,1401.300049,22.177076,3.438512,NaN,17.899754,5.764807,0.64,0.38,NaN,0.40,0.26,0.4200
37,BRITANNIA.NS,5120.500000,39.398956,24.154556,NaN,34.636099,15.309733,0.82,1.00,NaN,0.62,0.58,0.7550
38,HAVELLS.NS,1150.500000,33.823135,7.632195,NaN,33.076413,9.550749,0.78,0.78,NaN,0.56,0.48,0.6500
39,SHREECEM.NS,24085.000000,33.988667,9.431100,NaN,30.394816,12.989450,0.80,0.82,NaN,0.52,0.54,0.6700
40,GRASIM.NS,3087.699951,21.028017,2.102374,NaN,13.216398,4.900219,0.56,0.22,NaN,0.34,0.12,0.3100
41,TATASTEEL.NS,206.770004,10.998404,2.712769,NaN,10.450971,2.634354,0.14,0.32,NaN,0.16,0.10,0.1800
42,HEROMOTOCO.NS,4835.000000,15.164440,4.475762,NaN,12.027232,5.386056,0.36,0.56,NaN,0.26,0.16,0.3350
43,M&M.NS,3040.500000,18.991392,3.649543,NaN,10.737296,5.562058,0.52,0.44,NaN,0.18,0.18,0.3300
44,EICHERMOT.NS,7070.000000,26.664543,7.726522,NaN,32.555689,18.214718,0.72,0.80,NaN,0.54,0.64,0.6750
45,IOC.NS,138.259995,7.853276,0.867258,NaN,4.109124,2.093191,0.06,0.02,NaN,0.04,0.06,0.0450
46,SBICARD.NS,589.599976,16.267838,3.569483,NaN,75.386413,33.721651,0.40,0.42,NaN,0.87,0.80,0.6225
47,PIDILITIND.NS,1476.599976,48.695374,13.877688,NaN,41.699376,18.089749,0.92,0.96,NaN,0.68,0.62,0.7950
48,DMART.NS,4144.200195,58.444714,11.023334,NaN,52.403024,26.232405,1.00,0.88,NaN,0.74,0.74,0.8400
49,HDFCAMC.NS,2495.899902,28.424921,11.586041,NaN,26.187872,23.755835,0.76,0.90,NaN,0.50,0.72,0.7200

In [19]:
df=df.sort_values(by="Value Score",ascending=False)

In [20]:
df

,Ticker,Price,PE-ratio,PB-ratio,PS-ratio,EV/EBITDA,EV/GP,PE-Ratio_Percentile,PB-Ratio_Percentile,PS-Ratio_Percentile,EV/EBITDA_Percentile,EV/GP_Percentile,Value Score
48,DMART.NS,4144.200195,58.444714,11.023334,NaN,52.403024,26.232405,1.00,0.88,NaN,0.74,0.74,0.8400
26,TITAN.NS,4260.200195,49.756813,24.085938,NaN,48.435195,23.423066,0.96,0.98,NaN,0.70,0.70,0.8350
25,ADANIGREEN.NS,1525.699951,49.477158,13.027922,NaN,33.400840,30.351249,0.94,0.94,NaN,0.58,0.78,0.8100
27,DIVISLAB.NS,6623.000000,46.954030,10.482266,NaN,50.068627,26.640610,0.90,0.86,NaN,0.72,0.76,0.8100
47,PIDILITIND.NS,1476.599976,48.695374,13.877688,NaN,41.699376,18.089749,0.92,0.96,NaN,0.68,0.62,0.7950
23,TATAMOTORS.NS,2718.009177,23.592273,5.753018,NaN,75.386413,45.309444,0.68,0.70,NaN,0.87,0.89,0.7850
14,ASIANPAINT.NS,2686.699951,45.893230,12.048360,NaN,38.038899,16.346470,0.86,0.92,NaN,0.66,0.60,0.7600
37,BRITANNIA.NS,5120.500000,39.398956,24.154556,NaN,34.636099,15.309733,0.82,1.00,NaN,0.62,0.58,0.7550
3,INFY.NS,1197.500000,14.609312,5.198081,NaN,1093.840651,814.033092,0.34,0.68,NaN,1.00,1.00,0.7550
18,ULTRACEMCO.NS,10912.000000,24.926277,4.455898,NaN,75.386413,45.309444,0.70,0.54,NaN,0.87,0.89,0.7500
19,HDFCLIFE.NS,575.299988,46.924957,6.980356,NaN,58.832859,12.025826,0.88,0.72,NaN,0.76,0.52,0.7200
49,HDFCAMC.NS,2495.899902,28.424921,11.586041,NaN,26.187872,23.755835,0.76,0.90,NaN,0.50,0.72,0.7200
5,HINDUNILVR.NS,2121.500000,39.595154,10.227251,NaN,33.888950,15.124873,0.84,0.84,NaN,0.60,0.56,0.7100
13,HCLTECH.NS,1154.699951,14.415482,4.098199,NaN,1077.190087,624.707787,0.32,0.48,NaN,0.98,0.98,0.6900
11,ADANIENT.NS,3048.199951,53.869400,4.869088,NaN,37.223687,10.765717,0.98,0.62,NaN,0.64,0.50,0.6850
44,EICHERMOT.NS,7070.000000,26.664543,7.726522,NaN,32.555689,18.214718,0.72,0.80,NaN,0.54,0.64,0.6750
39,SHREECEM.NS,24085.000000,33.988667,9.431100,NaN,30.394816,12.989450,0.80,0.82,NaN,0.52,0.54,0.6700
7,BAJFINANCE.NS,889.400024,17.976105,4.850250,NaN,75.386413,22.510702,0.48,0.58,NaN,0.87,0.68,0.6525
38,HAVELLS.NS,1150.500000,33.823135,7.632195,NaN,33.076413,9.550749,0.78,0.78,NaN,0.56,0.48,0.6500
46,SBICARD.NS,589.599976,16.267838,3.569483,NaN,75.386413,33.721651,0.40,0.42,NaN,0.87,0.80,0.6225
4,ICICIBANK.NS,1262.099976,13.876246,2.489418,NaN,75.386413,45.309444,0.28,0.28,NaN,0.87,0.89,0.5800
35,ADANIPORTS.NS,1824.199951,23.531855,4.379884,NaN,21.361324,19.217751,0.66,0.50,NaN,0.46,0.66,0.5700
16,SUNPHARMA.NS,1782.199951,27.516460,5.122030,NaN,24.282533,8.535052,0.74,0.66,NaN,0.48,0.40,0.5700
10,KOTAKBANK.NS,377.450012,13.480357,2.072500,NaN,75.386413,45.309444,0.24,0.20,NaN,0.87,0.89,0.5500
2,HDFCBANK.NS,747.049988,11.888652,1.962265,NaN,75.386413,45.309444,0.16,0.18,NaN,0.87,0.89,0.5250
15,AXISBANK.NS,1272.300049,10.097619,1.838270,NaN,75.386413,45.309444,0.12,0.14,NaN,0.87,0.89,0.5050
24,INDUSINDBK.NS,904.799988,12.481459,1.071794,NaN,75.386413,45.309444,0.18,0.06,NaN,0.87,0.89,0.5000
6,SBIN.NS,977.700012,9.529786,1.524414,NaN,75.386413,45.309444,0.10,0.10,NaN,0.87,0.89,0.4900
8,BHARTIARTL.NS,1798.199951,21.551907,7.052594,NaN,10.440634,8.754300,0.62,0.76,NaN,0.14,0.44,0.4900
12,LT.NS,3953.199951,21.551163,4.975896,NaN,18.042499,5.685855,0.60,0.64,NaN,0.42,0.22,0.4700
29,MARUTI.NS,13050.000000,21.038420,3.828925,NaN,18.318721,7.702384,0.58,0.46,NaN,0.44,0.38,0.4650
36,CIPLA.NS,1401.300049,22.177076,3.438512,NaN,17.899754,5.764807,0.64,0.38,NaN,0.40,0.26,0.4200
9,ITC.NS,280.700012,15.856420,4.850862,NaN,12.106601,7.140017,0.38,0.60,NaN,0.30,0.36,0.4100
34,BAJAJFINSV.NS,1703.199951,18.506260,3.490250,NaN,11.956322,8.789035,0.50,0.40,NaN,0.24,0.46,0.4000
28,TECHM.NS,1483.500000,17.383010,4.441045,NaN,13.917303,6.212869,0.42,0.52,NaN,0.36,0.30,0.4000
33,DRREDDY.NS,1278.199951,19.814133,2.822730,NaN,15.514052,5.964326,0.54,0.34,NaN,0.38,0.28,0.3850
1,TCS.NS,2198.899902,13.291954,7.008960,NaN,10.856281,7.127766,0.22,0.74,NaN,0.22,0.34,0.3800
32,JSWSTEEL.NS,1284.000000,17.656523,3.132242,NaN,12.629194,5.725965,0.44,0.36,NaN,0.32,0.24,0.3400
42,HEROMOTOCO.NS,4835.000000,15.164440,4.475762,NaN,12.027232,5.386056,0.36,0.56,NaN,0.26,0.16,0.3350
43,M&M.NS,3040.500000,18.991392,3.649543,NaN,10.737296,5.562058,0.52,0.44,NaN,0.18,0.18,0.3300
40,GRASIM.NS,3087.699951,21.028017,2.102374,NaN,13.216398,4.900219,0.56,0.22,NaN,0.34,0.12,0.3100
22,POWERGRID.NS,285.649994,14.340636,2.642681,NaN,10.746495,8.733512,0.30,0.30,NaN,0.20,0.42,0.3050
0,RELIANCE.NS,1291.000000,17.954712,1.932505,NaN,12.065035,5.613055,0.46,0.16,NaN,0.28,0.20,0.2750
17,WIPRO.NS,198.369995,13.785324,2.362926,NaN,10.168374,6.444878,0.26,0.24,NaN,0.12,0.32,0.2350
41,TATASTEEL.NS,206.770004,10.998404,2.712769,NaN,10.450971,2.634354,0.14,0.32,NaN,0.16,0.10,0.1800
21,NTPC.NS,361.649994,12.782738,1.726714,NaN,8.364155,5.187402,0.20,0.12,NaN,0.10,0.14,0.1400
30,COALINDIA.NS,472.299988,8.263483,2.443605,NaN,6.067859,1.957229,0.08,0.26,NaN,0.08,0.02,0.1100
31,BPCL.NS,295.000000,7.436877,1.258677,NaN,3.741977,2.108563,0.04,0.08,NaN,0.02,0.08,0.0550
45,IOC.NS,138.259995,7.853276,0.867258,NaN,4.109124,2.093191,0.06,0.02,NaN,0.04,0.06,0.0450
20,ONGC.NS,264.750000,6.086708,0.895939,NaN,4.563303,1.962346,0.02,0.04,NaN,0.06,0.04,0.0400

In [21]:
df.head()

,Ticker,Price,PE-ratio,PB-ratio,PS-ratio,EV/EBITDA,EV/GP,PE-Ratio_Percentile,PB-Ratio_Percentile,PS-Ratio_Percentile,EV/EBITDA_Percentile,EV/GP_Percentile,Value Score
48,DMART.NS,4144.200195,58.444714,11.023334,NaN,52.403024,26.232405,1.00,0.88,NaN,0.74,0.74,0.840
26,TITAN.NS,4260.200195,49.756813,24.085938,NaN,48.435195,23.423066,0.96,0.98,NaN,0.70,0.70,0.835
25,ADANIGREEN.NS,1525.699951,49.477158,13.027922,NaN,33.400840,30.351249,0.94,0.94,NaN,0.58,0.78,0.810
27,DIVISLAB.NS,6623.000000,46.954030,10.482266,NaN,50.068627,26.640610,0.90,0.86,NaN,0.72,0.76,0.810
47,PIDILITIND.NS,1476.599976,48.695374,13.877688,NaN,41.699376,18.089749,0.92,0.96,NaN,0.68,0.62,0.795